"""0001_initial -- every table Aureon has (C-5, plan §8-§21, §30).

One revision rather than one per domain. The alternative was considered and rejected: a
migration per table means a deployment can sit half-migrated, and "half-migrated" on the
money path means an executor that can read a confirmed request and cannot record what the
broker said about it.

**There is no downgrade, and that is C-7.** See the function at the bottom for why.

Generated from ``aureon/storage/postgres/tables.py`` by alembic autogenerate and edited
only in this header and the downgrade. The tables are not re-written by hand here: a
migration hand-maintained beside a model is a migration that drifts from it, and
``scripts/migrate.py check`` compares the two.

Every timestamp renders as ``sa.DateTime(timezone=True)`` rather than as the application's
``UtcTimestamp``, so this file depends on SQLAlchemy alone -- a migration that has already
run in production must not break because an application class was renamed (decision 343).

Revision ID: 0001
Revises: (none -- this is the first)
"""
from __future__ import annotations

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision = "0001"
down_revision = None
branch_labels = None
depends_on = None

#: C-7's four. These may only ever GAIN columns and indexes, and nothing may drop them.
MONEY_TABLES = ("trade_requests", "trades", "audit_logs", "control_requests")


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('alerts',
    sa.Column('alert_id', sa.String(), nullable=False),
    sa.Column('schema_version', sa.Integer(), nullable=False),
    sa.Column('symbol', sa.String(), nullable=False),
    sa.Column('level', sa.Float(), nullable=False),
    sa.Column('side', sa.String(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('requested_by', sa.String(), nullable=False),
    sa.Column('note', sa.String(), nullable=True),
    sa.Column('cancelled_by', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('fired_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('fired_price', sa.Float(), nullable=True),
    sa.Column('fired_snapshot', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.PrimaryKeyConstraint('alert_id')
    )
    op.create_index('ix_alerts_armed', 'alerts', ['status', 'symbol'], unique=False)
    op.create_index('ix_alerts_expires', 'alerts', ['expires_at'], unique=False)
    op.create_table('assessments',
    sa.Column('assessment_id', sa.String(), nullable=False),
    sa.Column('schema_version', sa.Integer(), nullable=False),
    sa.Column('detection_id', sa.String(), nullable=True),
    sa.Column('symbol', sa.String(), nullable=False),
    sa.Column('rule_id', sa.String(), nullable=False),
    sa.Column('n', sa.Integer(), nullable=False),
    sa.Column('insufficient', sa.Boolean(), nullable=False),
    sa.Column('disagrees_with_detection', sa.Boolean(), nullable=False),
    sa.Column('history_source', sa.String(), nullable=True),
    sa.Column('real_days', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('trend_read', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('cohort_filter', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('confirmations', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('tp_estimates', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('sl_estimates', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('paired', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.PrimaryKeyConstraint('assessment_id')
    )
    op.create_index('ix_assessments_detection', 'assessments', ['detection_id'], unique=False)
    op.create_index('ix_assessments_provenance', 'assessments', ['history_source'], unique=False)
    op.create_index('ix_assessments_symbol_created', 'assessments', ['symbol', 'created_at'], unique=False)
    op.create_table('audit_logs',
    sa.Column('audit_id', sa.String(), nullable=False),
    sa.Column('schema_version', sa.Integer(), nullable=False),
    sa.Column('at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('actor', sa.String(), nullable=False),
    sa.Column('action', sa.String(), nullable=False),
    sa.Column('collection', sa.String(), nullable=True),
    sa.Column('document_id', sa.String(), nullable=True),
    sa.Column('from_status', sa.String(), nullable=True),
    sa.Column('to_status', sa.String(), nullable=True),
    sa.Column('reason', sa.String(), nullable=True),
    sa.Column('reconciliation', sa.Boolean(), nullable=False),
    sa.Column('detail', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.PrimaryKeyConstraint('audit_id')
    )
    op.create_index('ix_audit_logs_actor', 'audit_logs', ['actor', 'at'], unique=False)
    op.create_index('ix_audit_logs_at', 'audit_logs', ['at'], unique=False)
    op.create_index('ix_audit_logs_document', 'audit_logs', ['collection', 'document_id'], unique=False)
    op.create_table('control_requests',
    sa.Column('control_id', sa.String(), nullable=False),
    sa.Column('schema_version', sa.Integer(), nullable=False),
    sa.Column('kind', sa.String(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('target', sa.String(), nullable=False),
    sa.Column('symbol', sa.String(), nullable=True),
    sa.Column('volume', sa.Float(), nullable=True),
    sa.Column('requested_by', sa.String(), nullable=False),
    sa.Column('requested_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('executor_instance_id', sa.String(), nullable=True),
    sa.Column('lease_expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('failure_code', sa.String(), nullable=True),
    sa.Column('failure_message', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('control_id')
    )
    op.create_index('ix_control_requests_claim', 'control_requests', ['status', 'requested_at'], unique=False)
    op.create_index('ix_control_requests_lease', 'control_requests', ['lease_expires_at'], unique=False)
    op.create_table('daily_reviews',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('schema_version', sa.Integer(), nullable=False),
    sa.Column('market_date', sa.String(), nullable=False),
    sa.Column('symbol', sa.String(), nullable=True),
    sa.Column('generated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('evaluation_rule_id', sa.String(), nullable=True),
    sa.Column('review', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_daily_reviews_date', 'daily_reviews', ['market_date', 'symbol'], unique=False)
    op.create_table('detections',
    sa.Column('detection_id', sa.String(), nullable=False),
    sa.Column('schema_version', sa.Integer(), nullable=False),
    sa.Column('account_scope', sa.String(), nullable=False),
    sa.Column('symbol', sa.String(), nullable=False),
    sa.Column('timeframe', sa.String(), nullable=False),
    sa.Column('agent_name', sa.String(), nullable=False),
    sa.Column('agent_version', sa.String(), nullable=False),
    sa.Column('event_key', sa.String(), nullable=False),
    sa.Column('direction', sa.String(), nullable=True),
    sa.Column('candle_close_utc', sa.DateTime(timezone=True), nullable=False),
    sa.Column('candle_time_utc', sa.DateTime(timezone=True), nullable=False),
    sa.Column('timezone', sa.String(), nullable=False),
    sa.Column('market_date', sa.String(), nullable=False),
    sa.Column('price', sa.Float(), nullable=False),
    sa.Column('sequence_today', sa.Integer(), nullable=False),
    sa.Column('sequence_session', sa.Integer(), nullable=False),
    sa.Column('session', sa.String(), nullable=False),
    sa.Column('session_config_version', sa.String(), nullable=False),
    sa.Column('agent_params_snapshot', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('indicators', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('levels', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('volume_profile_ref', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('volatility', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('mtf', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.PrimaryKeyConstraint('detection_id')
    )
    op.create_index('ix_detections_agent_close', 'detections', ['agent_name', 'candle_close_utc'], unique=False)
    op.create_index('ix_detections_market_date', 'detections', ['market_date'], unique=False)
    op.create_index('ix_detections_symbol_close', 'detections', ['symbol', 'candle_close_utc'], unique=False)
    op.create_index('ix_detections_symbol_date', 'detections', ['symbol', 'market_date'], unique=False)
    op.create_table('heartbeats',
    sa.Column('service', sa.String(), nullable=False),
    sa.Column('schema_version', sa.Integer(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('instance_id', sa.String(), nullable=True),
    sa.Column('detail', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.PrimaryKeyConstraint('service')
    )
    op.create_table('market_day_frames',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('schema_version', sa.Integer(), nullable=False),
    sa.Column('symbol', sa.String(), nullable=False),
    sa.Column('market_date', sa.String(), nullable=False),
    sa.Column('timeframe', sa.String(), nullable=False),
    sa.Column('timezone', sa.String(), nullable=False),
    sa.Column('truncated', sa.Boolean(), nullable=False),
    sa.Column('complete', sa.Boolean(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('bars', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_market_day_frames_key', 'market_day_frames', ['symbol', 'market_date', 'timeframe'], unique=True)
    op.create_table('market_days',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('schema_version', sa.Integer(), nullable=False),
    sa.Column('symbol', sa.String(), nullable=False),
    sa.Column('market_date', sa.String(), nullable=False),
    sa.Column('timezone', sa.String(), nullable=False),
    sa.Column('complete', sa.Boolean(), nullable=False),
    sa.Column('open', sa.Float(), nullable=True),
    sa.Column('high', sa.Float(), nullable=True),
    sa.Column('low', sa.Float(), nullable=True),
    sa.Column('close', sa.Float(), nullable=True),
    sa.Column('bars', sa.Integer(), nullable=False),
    sa.Column('tick_volume', sa.BigInteger(), nullable=False),
    sa.Column('first_bar_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_bar_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('frames', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_market_days_complete', 'market_days', ['symbol', 'complete', 'market_date'], unique=False)
    op.create_index('ix_market_days_symbol_date', 'market_days', ['symbol', 'market_date'], unique=True)
    op.create_table('notifications',
    sa.Column('notification_id', sa.String(), nullable=False),
    sa.Column('schema_version', sa.Integer(), nullable=False),
    sa.Column('kind', sa.String(), nullable=False),
    sa.Column('symbol', sa.String(), nullable=False),
    sa.Column('ref_id', sa.String(), nullable=False),
    sa.Column('channel_id', sa.String(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('sent_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('message_id', sa.String(), nullable=True),
    sa.Column('failure_message', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('notification_id')
    )
    op.create_index('ix_notifications_ref', 'notifications', ['kind', 'ref_id'], unique=False)
    op.create_index('ix_notifications_status', 'notifications', ['status', 'sent_at'], unique=False)
    op.create_table('ops_events',
    sa.Column('event_id', sa.String(), nullable=False),
    sa.Column('schema_version', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('scope', sa.String(), nullable=True),
    sa.Column('service', sa.String(), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('since', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('onsets', sa.Integer(), nullable=False),
    sa.Column('detail', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('event_id')
    )
    op.create_index('ix_ops_events_active', 'ops_events', ['active', 'name'], unique=False)
    op.create_index('ix_ops_events_updated', 'ops_events', ['updated_at'], unique=False)
    op.create_table('sessions',
    sa.Column('session_doc_id', sa.String(), nullable=False),
    sa.Column('schema_version', sa.Integer(), nullable=False),
    sa.Column('session_id', sa.String(), nullable=False),
    sa.Column('account_scope', sa.String(), nullable=False),
    sa.Column('symbol', sa.String(), nullable=False),
    sa.Column('timeframe', sa.String(), nullable=False),
    sa.Column('session', sa.String(), nullable=False),
    sa.Column('market_date', sa.String(), nullable=False),
    sa.Column('timezone', sa.String(), nullable=False),
    sa.Column('session_config_version', sa.String(), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('ended_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('open', sa.Float(), nullable=True),
    sa.Column('high', sa.Float(), nullable=True),
    sa.Column('low', sa.Float(), nullable=True),
    sa.Column('close', sa.Float(), nullable=True),
    sa.Column('trend', sa.String(), nullable=True),
    sa.Column('change', sa.Float(), nullable=True),
    sa.Column('change_points', sa.Float(), nullable=True),
    sa.Column('range', sa.Float(), nullable=True),
    sa.Column('candle_count', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('session_doc_id')
    )
    op.create_index('ix_sessions_symbol_date', 'sessions', ['symbol', 'market_date'], unique=False)
    op.create_table('settings',
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('schema_version', sa.Integer(), nullable=False),
    sa.Column('settings_version', sa.Integer(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_by', sa.String(), nullable=True),
    sa.Column('value', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.PrimaryKeyConstraint('name')
    )
    op.create_table('setups',
    sa.Column('setup_id', sa.String(), nullable=False),
    sa.Column('schema_version', sa.Integer(), nullable=False),
    sa.Column('account_scope', sa.String(), nullable=False),
    sa.Column('symbol', sa.String(), nullable=False),
    sa.Column('timeframe', sa.String(), nullable=False),
    sa.Column('family', sa.String(), nullable=False),
    sa.Column('direction_context', sa.String(), nullable=False),
    sa.Column('state', sa.String(), nullable=False),
    sa.Column('market_date', sa.String(), nullable=False),
    sa.Column('invalidation_price', sa.Float(), nullable=True),
    sa.Column('opened_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('confirmed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('closed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_event_id', sa.String(), nullable=True),
    sa.Column('event_count', sa.Integer(), nullable=False),
    sa.Column('setup_version', sa.String(), nullable=False),
    sa.Column('anchor', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('linked_detection_ids', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('context_summary', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('reference', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('params_snapshot', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.PrimaryKeyConstraint('setup_id')
    )
    op.create_index('ix_setups_family_state', 'setups', ['family', 'state'], unique=False)
    op.create_index('ix_setups_symbol_date', 'setups', ['symbol', 'market_date'], unique=False)
    op.create_index('ix_setups_symbol_state', 'setups', ['symbol', 'state'], unique=False)
    op.create_index('ix_setups_updated', 'setups', ['updated_at'], unique=False)
    op.create_table('symbol_specs',
    sa.Column('symbol', sa.String(), nullable=False),
    sa.Column('schema_version', sa.Integer(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('spec', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.PrimaryKeyConstraint('symbol')
    )
    op.create_table('sync_batches',
    sa.Column('batch_id', sa.String(), nullable=False),
    sa.Column('schema_version', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('tables_sent', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('row_counts', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('failure_message', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('batch_id')
    )
    op.create_index('ix_sync_batches_started', 'sync_batches', ['started_at'], unique=False)
    op.create_table('system_state',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('schema_version', sa.Integer(), nullable=False),
    sa.Column('symbol', sa.String(), nullable=False),
    sa.Column('timeframe', sa.String(), nullable=False),
    sa.Column('market_state', sa.String(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('state', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_system_state_symbol', 'system_state', ['symbol', 'timeframe'], unique=True)
    op.create_table('trade_notes',
    sa.Column('note_id', sa.String(), nullable=False),
    sa.Column('schema_version', sa.Integer(), nullable=False),
    sa.Column('trade_id', sa.String(), nullable=False),
    sa.Column('author', sa.String(), nullable=False),
    sa.Column('text', sa.String(), nullable=False),
    sa.Column('at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('note_id')
    )
    op.create_index('ix_trade_notes_trade', 'trade_notes', ['trade_id', 'at'], unique=False)
    op.create_table('trade_requests',
    sa.Column('request_id', sa.String(), nullable=False),
    sa.Column('schema_version', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('symbol', sa.String(), nullable=False),
    sa.Column('order_type', sa.String(), nullable=False),
    sa.Column('volume', sa.Float(), nullable=False),
    sa.Column('price', sa.Float(), nullable=True),
    sa.Column('sl', sa.Float(), nullable=True),
    sa.Column('tp', sa.Float(), nullable=True),
    sa.Column('deviation_points', sa.Integer(), nullable=False),
    sa.Column('filling_mode', sa.String(), nullable=True),
    sa.Column('requested_by', sa.String(), nullable=False),
    sa.Column('requested_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('confirmed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('confirmed_by', sa.String(), nullable=True),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('confirmation_version', sa.Integer(), nullable=False),
    sa.Column('detection_id', sa.String(), nullable=True),
    sa.Column('link_type', sa.String(), nullable=True),
    sa.Column('executor_instance_id', sa.String(), nullable=True),
    sa.Column('lease_expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('execution_started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('execution_attempt_id', sa.String(), nullable=True),
    sa.Column('comment_token', sa.String(), nullable=True),
    sa.Column('magic', sa.BigInteger(), nullable=True),
    sa.Column('order_ticket', sa.BigInteger(), nullable=True),
    sa.Column('position_id', sa.BigInteger(), nullable=True),
    sa.Column('deal_ids', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('fill_price', sa.Float(), nullable=True),
    sa.Column('filled_volume', sa.Float(), nullable=True),
    sa.Column('failure_code', sa.String(), nullable=True),
    sa.Column('failure_message', sa.String(), nullable=True),
    sa.Column('quote', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('last_reconciled_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_synced_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('request_id')
    )
    op.create_index('ix_trade_requests_claim', 'trade_requests', ['status', 'confirmed_at'], unique=False)
    op.create_index('ix_trade_requests_detection', 'trade_requests', ['detection_id'], unique=False)
    op.create_index('ix_trade_requests_lease', 'trade_requests', ['lease_expires_at'], unique=False)
    op.create_index('ix_trade_requests_symbol_status', 'trade_requests', ['symbol', 'status'], unique=False)
    op.create_table('trades',
    sa.Column('trade_id', sa.String(), nullable=False),
    sa.Column('schema_version', sa.Integer(), nullable=False),
    sa.Column('mt5_position_id', sa.BigInteger(), nullable=False),
    sa.Column('trade_request_id', sa.String(), nullable=True),
    sa.Column('source', sa.String(), nullable=False),
    sa.Column('symbol', sa.String(), nullable=False),
    sa.Column('direction', sa.String(), nullable=False),
    sa.Column('volume', sa.Float(), nullable=False),
    sa.Column('open_price', sa.Float(), nullable=False),
    sa.Column('open_time_utc', sa.DateTime(timezone=True), nullable=False),
    sa.Column('timezone', sa.String(), nullable=False),
    sa.Column('sl', sa.Float(), nullable=True),
    sa.Column('tp', sa.Float(), nullable=True),
    sa.Column('magic', sa.BigInteger(), nullable=True),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('closed_volume', sa.Float(), nullable=False),
    sa.Column('close_price', sa.Float(), nullable=True),
    sa.Column('close_time_utc', sa.DateTime(timezone=True), nullable=True),
    sa.Column('close_reason', sa.String(), nullable=False),
    sa.Column('close_reason_raw', sa.String(), nullable=True),
    sa.Column('realized_pnl', sa.Float(), nullable=True),
    sa.Column('commission', sa.Float(), nullable=False),
    sa.Column('swap', sa.Float(), nullable=False),
    sa.Column('detection_id', sa.String(), nullable=True),
    sa.Column('link_type', sa.String(), nullable=True),
    sa.Column('deal_ids', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('excursion', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('last_reconciled_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_synced_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('trade_id')
    )
    op.create_index('ix_trades_open_time', 'trades', ['open_time_utc'], unique=False)
    op.create_index('ix_trades_position', 'trades', ['mt5_position_id'], unique=True)
    op.create_index('ix_trades_request', 'trades', ['trade_request_id'], unique=False)
    op.create_index('ix_trades_symbol_status', 'trades', ['symbol', 'status'], unique=False)
    op.create_table('weekly_reviews',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('schema_version', sa.Integer(), nullable=False),
    sa.Column('iso_year', sa.Integer(), nullable=False),
    sa.Column('iso_week', sa.Integer(), nullable=False),
    sa.Column('symbol', sa.String(), nullable=True),
    sa.Column('generated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('evaluation_rule_id', sa.String(), nullable=True),
    sa.Column('review', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_weekly_reviews_week', 'weekly_reviews', ['iso_year', 'iso_week', 'symbol'], unique=False)
    op.create_table('detection_evaluations',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('schema_version', sa.Integer(), nullable=False),
    sa.Column('detection_id', sa.String(), nullable=False),
    sa.Column('rule_id', sa.String(), nullable=False),
    sa.Column('evaluation_rule_id', sa.String(), nullable=True),
    sa.Column('reference_price', sa.String(), nullable=False),
    sa.Column('reference_value', sa.Float(), nullable=True),
    sa.Column('context_tags', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('horizons', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['detection_id'], ['detections.detection_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('detection_id', 'rule_id', name='uq_detection_evaluation')
    )
    op.create_index('ix_detection_evaluations_rule', 'detection_evaluations', ['rule_id'], unique=False)
    op.create_table('setup_evaluations',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('schema_version', sa.Integer(), nullable=False),
    sa.Column('setup_id', sa.String(), nullable=False),
    sa.Column('rule_id', sa.String(), nullable=False),
    sa.Column('evaluation_rule_id', sa.String(), nullable=True),
    sa.Column('family', sa.String(), nullable=False),
    sa.Column('direction_context', sa.String(), nullable=False),
    sa.Column('symbol', sa.String(), nullable=False),
    sa.Column('timeframe', sa.String(), nullable=False),
    sa.Column('market_date', sa.String(), nullable=False),
    sa.Column('setup_version', sa.String(), nullable=False),
    sa.Column('reference_price', sa.String(), nullable=False),
    sa.Column('reference_value', sa.Float(), nullable=True),
    sa.Column('context_summary', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('horizons', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['setup_id'], ['setups.setup_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('setup_id', 'rule_id', name='uq_setup_evaluation')
    )
    op.create_index('ix_setup_evaluations_cohort', 'setup_evaluations', ['symbol', 'family', 'market_date'], unique=False)
    op.create_table('setup_events',
    sa.Column('event_id', sa.String(), nullable=False),
    sa.Column('schema_version', sa.Integer(), nullable=False),
    sa.Column('setup_id', sa.String(), nullable=False),
    sa.Column('event_type', sa.String(), nullable=False),
    sa.Column('from_state', sa.String(), nullable=False),
    sa.Column('to_state', sa.String(), nullable=False),
    sa.Column('linked_detection_id', sa.String(), nullable=True),
    sa.Column('market_time_utc', sa.DateTime(timezone=True), nullable=False),
    sa.Column('timezone', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('context_snapshot', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('reason', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['setup_id'], ['setups.setup_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('event_id')
    )
    op.create_index('ix_setup_events_setup_created', 'setup_events', ['setup_id', 'created_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Refused (C-7). The money tables have no destructive downgrade.

    ``trade_requests``, ``trades``, ``audit_logs`` and ``control_requests`` hold the only
    record of what a human asked for, what was sent to the broker and what came back. A
    downgrade that dropped them would not be a rollback -- it would be indistinguishable
    from the trades never having happened, while MT5 still held the positions.

    This revision creates every table, so its downgrade would drop every table. Refusing is
    therefore the whole of C-7 for revision 0001, not a partial application of it.

    **What to do instead.** Tearing down a DEVELOPMENT database is an operator action
    taken deliberately, with the database named out loud: ``DROP DATABASE aureon_test``.
    ``alembic downgrade`` names nothing, which is exactly why it is the wrong tool here
    (decision 344). A real database is restored from a backup rather than torn down, and
    that tooling arrives with C-3 in S-6.
    """
    raise RuntimeError(
        "0001_initial has no downgrade: it would drop "
        + ", ".join(MONEY_TABLES)
        + ", which hold the only record of every order this system has sent (C-7). "
        "To tear down a development database, drop the database by name instead."
    )
