"""Aureon domain contracts.

Models live ONLY here (CLAUDE.md). Adding one means regenerating
``docs/CONTRACTS.md`` with ``python scripts/gen_contracts.py`` and committing the
result alongside the change, so the documented contract and the code cannot drift
apart -- and so the Vue types generated from it in Phase 8 stay truthful.
"""

from aureon.models.audit import AuditRecord
from aureon.models.base import (
    SCHEMA_VERSION,
    AureonDocument,
    AureonModel,
    MarketTime,
    UtcDatetime,
    to_utc,
    utc_now,
)
from aureon.models.broker import (
    AccountInfo,
    BrokerDeal,
    BrokerOrder,
    BrokerPosition,
)
from aureon.models.control import ControlRequest
from aureon.models.detection import (
    CandleContext,
    Detection,
    IndicatorSnapshot,
    SessionContext,
)
from aureon.models.enums import (
    CONTROL_REQUEST_TRANSITIONS,
    HORIZON_TRANSITIONS,
    TERMINAL_REQUEST_STATUSES,
    TRADE_REQUEST_TRANSITIONS,
    TRADE_TRANSITIONS,
    ControlRequestKind,
    ControlRequestStatus,
    DealEntry,
    Direction,
    ExcursionSource,
    ExecutionClassification,
    FailureCode,
    FillingMode,
    Freshness,
    HorizonKind,
    HorizonStatus,
    LinkType,
    MarketState,
    OrderType,
    PathClassification,
    ReferencePrice,
    SessionName,
    ThresholdUnit,
    Timeframe,
    TradeRequestStatus,
    TradeSource,
    TradeStatus,
    TransitionError,
    assert_control_request_transition,
    assert_horizon_transition,
    assert_trade_request_transition,
    assert_trade_transition,
    assert_transition,
    is_terminal,
)
from aureon.models.evaluation import (
    DetectionEvaluation,
    EvaluationRule,
    Horizon,
    HorizonResult,
    threshold_key,
)
from aureon.models.identity import (
    COMMENT_HASH_CHARS,
    COMMENT_PREFIX,
    DETECTION_ID_COMPONENTS,
    comment_token,
    detection_id,
    detection_id_components,
    evaluation_doc_id,
    execution_attempt_id,
)
from aureon.models.market import Candle, QuoteSnapshot, SymbolInfo
from aureon.models.profile import (
    MAX_PROFILE_BINS,
    PROFILE_SCOPES,
    VOLATILITY_REGIMES,
    ProfileBin,
    VolatilityContext,
    VolumeProfile,
    VolumeProfileRef,
)
from aureon.models.review import (
    DailyReview,
    HorizonOutcome,
    InferredLink,
    ReviewBase,
    ThresholdOutcome,
    WeeklyReview,
)
from aureon.models.session import (
    TREND_DOWN,
    TREND_FLAT,
    TREND_UP,
    TRENDS,
    SessionSummary,
)
from aureon.models.settings import ExecutionSettings, ResolvedLimits, SymbolLimits
from aureon.models.system import (
    DEFAULT_OFFLINE_AFTER_SECONDS,
    DEFAULT_STALE_AFTER_SECONDS,
    Heartbeat,
    SymbolState,
    SystemState,
    freshness_of,
)
from aureon.models.trade import (
    CLOSE_REASON_CONVENTION,
    BrokerOrderRequest,
    BrokerOrderResult,
    Excursion,
    PendingOrder,
    Trade,
    TradeRequest,
)

# Every stored document, in the order CONTRACTS.md renders them.
DOCUMENT_MODELS: tuple[type[AureonDocument], ...] = (
    Detection,
    DetectionEvaluation,
    TradeRequest,
    Trade,
    ControlRequest,
    AuditRecord,
    Heartbeat,
    SystemState,
    ExecutionSettings,
    SessionSummary,
    DailyReview,
    WeeklyReview,
)

__all__ = [
    "SCHEMA_VERSION",
    "AureonDocument",
    "AureonModel",
    "MarketTime",
    "UtcDatetime",
    "to_utc",
    "utc_now",
    "AuditRecord",
    "AccountInfo",
    "BrokerDeal",
    "BrokerOrder",
    "BrokerPosition",
    "ControlRequest",
    "CandleContext",
    "Detection",
    "IndicatorSnapshot",
    "SessionContext",
    "CONTROL_REQUEST_TRANSITIONS",
    "HORIZON_TRANSITIONS",
    "TERMINAL_REQUEST_STATUSES",
    "TRADE_REQUEST_TRANSITIONS",
    "TRADE_TRANSITIONS",
    "ControlRequestKind",
    "ControlRequestStatus",
    "DealEntry",
    "Direction",
    "ExcursionSource",
    "ExecutionClassification",
    "FailureCode",
    "FillingMode",
    "Freshness",
    "HorizonKind",
    "HorizonStatus",
    "LinkType",
    "MarketState",
    "OrderType",
    "PathClassification",
    "ReferencePrice",
    "ThresholdUnit",
    "SessionName",
    "Timeframe",
    "TradeRequestStatus",
    "TradeSource",
    "TradeStatus",
    "TransitionError",
    "assert_control_request_transition",
    "assert_horizon_transition",
    "assert_trade_request_transition",
    "assert_trade_transition",
    "assert_transition",
    "is_terminal",
    "DetectionEvaluation",
    "EvaluationRule",
    "Horizon",
    "HorizonResult",
    "threshold_key",
    "COMMENT_HASH_CHARS",
    "COMMENT_PREFIX",
    "DETECTION_ID_COMPONENTS",
    "comment_token",
    "detection_id",
    "detection_id_components",
    "evaluation_doc_id",
    "execution_attempt_id",
    "Candle",
    "QuoteSnapshot",
    "SymbolInfo",
    "MAX_PROFILE_BINS",
    "PROFILE_SCOPES",
    "VOLATILITY_REGIMES",
    "ProfileBin",
    "VolatilityContext",
    "VolumeProfile",
    "VolumeProfileRef",
    "DailyReview",
    "HorizonOutcome",
    "InferredLink",
    "ReviewBase",
    "ThresholdOutcome",
    "WeeklyReview",
    "SessionSummary",
    "TRENDS",
    "TREND_UP",
    "TREND_DOWN",
    "TREND_FLAT",
    "ExecutionSettings",
    "ResolvedLimits",
    "SymbolLimits",
    "DEFAULT_OFFLINE_AFTER_SECONDS",
    "DEFAULT_STALE_AFTER_SECONDS",
    "Heartbeat",
    "SymbolState",
    "SystemState",
    "freshness_of",
    "CLOSE_REASON_CONVENTION",
    "BrokerOrderRequest",
    "BrokerOrderResult",
    "Excursion",
    "PendingOrder",
    "Trade",
    "TradeRequest",
    "DOCUMENT_MODELS",
]
